### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory on latest commit

### ISSUE THREAD

**Issue by Akrai** [TamtamHero/fw-fanctrl#35]
Just updated the AUR package after last commits. Now it's not running. Tried to reinstall the package, no luck

$ fw-fanctrl 
Traceback (most recent call last):
  File "/usr/bin/fw-fanctrl", line 320, in <module>
    main()
  File "/usr/bin/fw-fanctrl", line 301, in main
    client_socket.connect(COMMANDS_SOCKET_FILE_PATH)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by OmegaLambda1998** [comment]
Same issue here, it looks like COMMANDS_SOCKET_FILE_PATH only gets initialised if a FanController is instantiated, however if not using --run, this never happens

**Comment by OmegaLambda1998** [comment]
As a temporary patch, create a file called `override.conf` in `/etc/systemd/system/fw-fanctrl.service.d` with the following"

```
[Service]
ExecStart=
ExecStart=/usr/bin/python3 /usr/bin/fw-fanctrl --run --config "/etc/fw-fanctrl/config.json" --no-log
ExecStopPost=
ExecStopPost=/bin/sh -c "ectool autofanctrl"
```

This got it working again for me, basically just taking the source code service file (https://github.com/TamtamHero/fw-fanctrl/blob/main/services/fw-fanctrl.service) and applying it

**Comment by leopoldhub** [comment]
Hi, as explained [here](https://github.com/TamtamHero/fw-fanctrl/pull/29#issuecomment-2116895643), we are not the maintainers of the AUR package and cannot guarantee that it will work.
The AUR package imports external outdated service files, please contact the AUR maintainer instead.
Please use the script installation for the time being (as the AUR version should have done to begin with...)

**Comment by leopoldhub** [comment]
I have contacted the AUR package maintainer, who should be patching it soon

**Comment by icedream** [comment]
Package maintainer here, I'm currently going over the current packaging complications I have with @leopoldhub via mail. I'll have time to hotfix the package files this evening after work but I intend to follow up with a better solution. Hopefully from there we find a more permanent solution soon.

**Comment by icedream** [comment]
We're taking care of long-term fixes in https://github.com/TamtamHero/fw-fanctrl/pull/37, the error should no longer happen on the AUR package where a hotfix has been applied a few days ago.

**Comment by icedream** [comment]
I just updated with the long-term fixes applied so all the service and script files should now originate from the repository but I'm still seeing it:

```
May 23 20:50:43 icedream-framework python3[2583794]: Traceback (most recent call last):
May 23 20:50:43 icedream-framework python3[2583794]:   File "/usr/bin/fw-fanctrl", line 323, in <module>
May 23 20:50:43 icedream-framework python3[2583794]:     main()
May 23 20:50:43 icedream-framework python3[2583794]:   File "/usr/bin/fw-fanctrl", line 304, in main
May 23 20:50:43 icedream-framework python3[2583794]:     client_socket.connect(COMMANDS_SOCKET_FILE_PATH)
May 23 20:50:43 icedream-framework python3[2583794]: ConnectionRefusedError: [Errno 111] Connection refused
```

I'm testing this on a Framework 16. Anyone else who still runs into this>

**Comment by icedream** [comment]
Ignore my previous comment if you see it via mail notification, I had a silly override still installed that I thought I removed. All good now. 👍🏻

**Comment by leopoldhub** [comment]
Made me panic for a bit 👀

**Comment by leopoldhub** [comment]
Hi everyone, the AUR package have been fixed (thanks to the wonderful work of @icedream).
Did any of you experience any kind of unexpected behaviour with the latest package version?
If not, I would like to close this issue.
Have a nice day

**Comment by Akrai** [comment]
Working properly here

**Comment by leopoldhub** [comment]
It seems that everything has been resolved, so I will then close the issue.

**Comment by skerit** [comment]
@leopoldhub I just installed `fw-fanctrl-git` (r38.f0d8d77-2), `fw-fanctrl-ui-git` (r1.120f20e-1) and `fw-ectool-git` from the AUR, but I still get the error:

```
$ fw-fanctrl                                                                                                                                                                                                   ma 22 jul 2024 11:18:05
Traceback (most recent call last):
  File "/usr/bin/fw-fanctrl", line 329, in <module>
    main()
  File "/usr/bin/fw-fanctrl", line 310, in main
    client_socket.connect(COMMANDS_SOCKET_FILE_PATH)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by icedream** [comment]
@skerit The package should automatically update to the latest git (at this point that would be `r45.dc6558e`).
